Repository rahulsainlll/git-trace, pull requests merged in 2024-11, with the labels that each got.

#160 fix: header and git issue
  components/page-header.tsx
Labels: bug, level2, gssoc-ext

#165 BUG : Fixed visible password length message
  app/auth/signin/page.tsx
Labels: bug, level1, gssoc-ext

#173 "Feature : Progressbar & ScrollToTop button added"
  app/provider.tsx
  components/Progressbar.tsx
  package-lock.json
  package.json
Labels: enhancement, level2, gssoc-ext

#174 Add Copyright Line to Footer
  components/ui/footer.tsx
Labels: enhancement, level1, gssoc-ext

#175 enhancement: faq redesign using shadcn-ui
  app/api/popular/route.ts
  app/faq/page.tsx
  components/ui/accordion.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/sitemap-0.xml
  tailwind.config.ts
Labels: enhancement, level2, gssoc-ext
