Repository rahulsainlll/git-trace, pull requests merged in 2024-10, with the labels that each got.

#22 fix: both Search buttons get's updated when clicked on one. #16
  app/page.tsx
Labels: good first issue, Level 1, gssoc-ext, hacktoberfest-accepted, gssoc-extd, hacktoberfest, gssoc, gssoc24-ext

#15 Created a static Blog-Page #4
  app/blog/[id]/page.tsx
  app/blog/page.tsx
  components/page-header.tsx
  components/ui/blog-card.tsx
Labels: Level 2, gssoc-ext, hacktoberfest-accepted, gssoc-extd, hacktoberfest, gssoc, gssoc24-ext, frontend

#26 implemented todo functionality #9
  app/api/search/repositories/route.ts
  app/api/todos/[todoId]/route.ts
  app/api/todos/route.ts
  app/dashboard/page.tsx
  components/boomarkRow.tsx
  package-lock.json
  prisma/migrations/20241002185804_added_todo_schema/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement, Level 3, gssoc-ext, hacktoberfest-accepted, gssoc-extd, hacktoberfest, gssoc, gssoc24-ext, frontend

#46 Added support for footer links
  components/ui/footer.tsx
Labels: enhancement, level1, hacktoberfest, gssoc24-ext

#44 added readme install guide
  README.md
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest, gssoc24-ext

#54 added button Todos
  app/dashboard/page.tsx
  components/boomarkRow.tsx
Labels: enhancement, level1, gssoc-extd, hacktoberfest

#57 Changed the img to Image in Blog card component
  components/ui/blog-card.tsx
  next.config.mjs
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#63 Pagination added in blog page
  app/blog/page.tsx
  components/pagination.tsx
  components/ui/blog-card.tsx
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#55 new feature and solved conflict
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/documentation_update.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/general_issue.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  app/about/page.tsx
  components/auth.tsx
  components/page-header.tsx
  components/ui/footer.tsx
Labels: documentation, level2, gssoc-ext, hacktoberfest-accepted

#76 Design : Added the Contributors page
  app/contributor/page.tsx
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, Design, hacktoberfest

#97 added highlighted active page in navbar
  components/page-header.tsx
Labels: good first issue, level2, gssoc-ext, hacktoberfest-accepted, frontend, hacktoberfest

#75 added avatar and fixed the button style
  components/UserAccDropDown.tsx
  components/UserImage.tsx
  components/page-header.tsx
  components/ui/avatar.tsx
  package.json
Labels: level2, gssoc-ext, hacktoberfest-accepted, Design, hacktoberfest

#88 Implement FAQ Section for the Website (#83)
  app/faq/page.tsx
  components/page-header.tsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#90 #Add Code of Conduct
  Code_Of_Conduct.md
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#74 change logout button style
  components/auth.tsx
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#89 search history added
  app/page.tsx
Labels: level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#85 Added the contributors page in the navbar (header)
  components/page-header.tsx
Labels: enhancement

#117 Updated the readme file with featured in
  README.md
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#126 Add Delete Button to Delete recent searches
  app/page.tsx
Labels: level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#128 fixed dark mode issue in login/signup page
  app/auth/signin/page.tsx
  app/auth/signup/page.tsx
  package-lock.json
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#133 added confirm password functionality
  app/auth/signup/page.tsx
  package-lock.json
  package.json
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#130 📑 Feature Request: Issues Listing Page
  app/issues/page.tsx
  app/page.tsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#111 Enhanced the ui design of the login and signup pages.
  app/auth/signin/page.tsx
  app/auth/signup/page.tsx
  package-lock.json
  package.json
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#122 Added the infinite scroll in the issues section of home page
  app/api/search/issues/route.ts
  app/page.tsx
  package-lock.json
  package.json
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#131 📑 Feature Request: Add Multi-Language Support for Global Accessibility
  app/globals.css
  app/layout.tsx
  components/GoogleTranslate.tsx
  components/page-header.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#132 Fix: Poor UI/UX in Todo Feature
  components/boomarkRow.tsx
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#144 Added bar/line chart for issues and pie chart for open vs closed issues
  app/issues/page.tsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#138 Fix #118/UI bugs
  app/auth/signin/page.tsx
  app/auth/signup/page.tsx
  app/contributor/page.tsx
  app/popular/page.tsx
  components/boomarkRow.tsx
  components/page-header.tsx
  components/ui/Pageloader.tsx
  components/ui/footer.tsx
Labels: bug, level3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#150 Added auto scrollable testimonial
  app/testimonial/page.tsx
  components/page-header.tsx
  package-lock.json
  public/profilePic.jpg
Labels: enhancement, level3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#153 Add Search Filter Feature
  app/popular/page.tsx
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#155 Issue open/close message workflow automation🚀
  .github/workflows/issue-open-close.yml
Labels: level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#159 Enhancement of Contributing.md
  CONTRIBUTING.md
Labels: documentation, level2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#129 Chatbot Added
  app/layout.tsx
  components/chatbot.tsx
Labels: level3, gssoc-ext, hacktoberfest-accepted, hacktoberfest
